-- backend/api/migrations/final_cms_completion.sql
-- Idempotent Final Production CMS Seeding and Table Structures

-- 1. Seed example Viva Studio services (or update them)
INSERT INTO `services` (id, title, slug, short_description, detail_description, category, image_url, video_url, suitable_for, benefits, process, faq, sort_order, seo_title, seo_description, is_active)
VALUES
(
  1,
  'Reformer Pilates',
  'reformer-pilates',
  'Vücudunuzu esnetin, güçlendirin ve duruşunuzu düzeltin.',
  'Aletli pilates ile kaslarınızı uzatın ve güçlendirin. Deneyimli eğitmenlerimiz eşliğinde duruş bozukluklarını giderin ve esnekliğinizi artırın. Birebir veya grup seansları mevcuttur.',
  'Pilates',
  'https://images.unsplash.com/photo-1518611012118-696072aa579a?auto=format&fit=crop&q=80&w=1200',
  '',
  'Duruş bozukluğu olanlar, kas gücünü artırmak isteyenler ve sırt/bel ağrısı yaşayanlar için uygundur.',
  'Esneklik artışı, Core bölgesi güçlendirme, Duruş bozukluğu düzeltme, Sırt ve bel ağrılarında azalma',
  'Eğitmen eşliğinde kişisel duruş analizi yapılır, ardından aletli reformer üzerinde kişiselleştirilmiş hareket programı uygulanır.',
  'Haftada kaç gün yapılmalı?:Haftada 2 veya 3 gün idealdir.\nKilo verdirir mi?:Sıkılaşma ve bölgesel incelme sağlar.',
  1,
  'Reformer Pilates - Viva Studio Tuzla',
  'Aletli Reformer Pilates seansları ile duruşunuzu düzeltin ve core bölgenizi güçlendirin. Tuzla Pilates stüdyomuzda profesyonel eğitmenler sizi bekliyor.',
  1
),
(
  2,
  'EMS Antrenmanı',
  'ems-antrenmani',
  '20 dakikada 3 saatlik spor etkisi yaratın.',
  'Elektriksel kas uyarımı (EMS) teknolojisi ile tüm ana kas gruplarınızı aynı anda çalıştırın. Zamanı kısıtlı olanlar için mükemmel bir fitness çözümüdür.',
  'Fitness',
  'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?auto=format&fit=crop&q=80&w=1200',
  '',
  'Zaman tasarrufu yapmak isteyenler, hızlı kas gelişimi ve eklem dostu egzersiz arayanlar.',
  'Zaman tasarrufu, Hızlı kas gelişimi, Eklem dostu egzersiz, Metabolizma hızlandırma',
  'EMS yeleği giyildikten sonra eğitmen eşliğinde 20 dakikalık aktif fonksiyonel egzersizler uygulanır.',
  'EMS güvenli midir?:Evet, düşük frekanslı akımlar kasları uyarır ve eklemleri zorlamaz.',
  2,
  'EMS Antrenmanı - 20 Dakikada Değişim | Viva Studio',
  'Elektriksel kas uyarımı (EMS) ile 20 dakikada 3 saatlik egzersiz etkisi. Kas gelişimi ve kilo verme hedefleriniz için Tuzla Viva Studio.',
  1
),
(
  3,
  'G5 Masajı',
  'g5-masaji',
  'Titreşimli masaj ile bölgesel incelme ve pürüzsüz cilt.',
  'Özel G5 masaj cihazı ile uygulanan titreşim ve ritmik vuruşlar sayesinde selülit görünümünü hafifletin, ödem atımını hızlandırın ve cildinizi sıkılaştırın.',
  'Bölgesel İncelme',
  'https://images.unsplash.com/photo-1519823551278-64ac92734fb1?auto=format&fit=crop&q=80&w=1200',
  '',
  'Selülit problemi olanlar, bölgesel ödem ve sıkılaşma ihtiyacı hissedenler için idealdir.',
  'Selülit tedavisinde etkilidir, Ödem atmayı destekler, Cilt sıkılaştırma, Kan dolaşımı artışı',
  'Titreşimli G5 başlığı ile belirlenen bölgelere ritmik basınç ve yağ yakıcı jeller yardımıyla masaj uygulanır.',
  'Kaç seans gereklidir?:Genelde 10 seanslık kürler halinde uygulanır.',
  3,
  'G5 Selülit Masajı & Sıkılaşma | Viva Studio',
  'G5 masajı ile selülit görünümünü yok edin, sıkılaşın ve vücudunuzdaki ödemi kolayca atın. Tuzla bölgesel incelme.',
  1
),
(
  4,
  'Vacu Active',
  'vacu-active',
  'Vakum teknolojisi ile bölgesel incelme ve kalori yakımı.',
  'Kızılötesi ve vakum teknolojisine sahip kabin içinde yürüyüş yaparak normal bir yürüyüşten 4 kat daha fazla kalori yakın ve selülit görünümünü azaltın.',
  'Bölgesel İncelme',
  'https://images.unsplash.com/photo-1574680093662-425eb33d596c?auto=format&fit=crop&q=80&w=1200',
  '',
  'Hızlı kalori yakmak isteyenler, selülitlerini azaltmak ve bölgesel incelme hedefleyenler.',
  '4 kata kadar daha hızlı kalori yakımı, Bölgesel incelme, Selülit görünümünde azalma, Kan dolaşımı hızlandırma',
  'Kapsül içine girilerek 30 dakikalık kontrollü yürüyüş veya koşu programı uygulanır.',
  'Seans süresi nedir?:Her seans standart 30 dakikadır.',
  4,
  'Vacu Active Vakumlu Yürüyüş | Viva Studio',
  'Vakum ve kızılötesi teknolojisi ile bölgesel yağ yakımı ve selülit tedavisi sağlayan Vacu Active seansları Viva Studio stüdyomuzda.',
  1
),
(
  5,
  'Bölgesel İncelme',
  'bolgesel-incelme',
  'Hedeflenen bölgelerde etkili yağ yakımı ve şekillenme.',
  'Vücudunuzun karın, kalça, basen ve kol gibi inatçı yağ biriken bölgelerinde teknolojik cihazlar ve kombine kürler ile incelme ve sıkılaşma sağlayın.',
  'Bölgesel İncelme',
  'https://images.unsplash.com/photo-1518611012118-696072aa579a?auto=format&fit=crop&q=80&w=800',
  '',
  'Diyet ve spora rağmen bölgesel yağlanmadan kurtulamayanlar.',
  'Noktasal yağ yakımı, Gözle görülür incelme, Sıkı ve şekilli hatlar',
  'Kişisel vücut analizinden sonra G5, Vacu Active and beslenme yönlendirmeleri ile kişiye özel bir incelme kürü programlanır.',
  'Ağrılı bir işlem midir?:Hayır, ağrısız ve konforlu teknolojik uygulamalar kullanılır.',
  5,
  'Profesyonel Bölgesel İncelme Kürleri | Viva Studio',
  'İnatçı bölgesel yağlara veda edin. En güncel bölgesel incelme teknolojileri ve uzman seansları Viva Studio kalitesiyle.',
  1
),
(
  6,
  'Mat Pilates',
  'mat-pilates',
  'Vücut ağırlığıyla denge, esneklik ve zihin-beden uyumu.',
  'Mat üzerinde, minder egzersizleri ve direnç bantları kullanarak vücudunuzun esnekliğini, duruş dengesini ve derin core kaslarını güçlendirin.',
  'Pilates',
  'https://images.unsplash.com/photo-1599058917212-d750089bc07e?auto=format&fit=crop&q=80&w=800',
  '',
  'Her yaş ve kondisyon seviyesindeki bireyler, esneklik ve postür düzeltmek isteyenler.',
  'Esneklik ve denge geliştirme, Doğal postür koruma, Zihin ve beden koordinasyonu',
  'Mat üzerinde nefes kontrolü eşliğinde kontrollü güç ve esneme egzersizleri uygulanır.',
  'Evde yapılabilir mi?:Stüdyomuzda profesyonel eğitmen gözetiminde doğru formda öğrenilmesi önerilir.',
  6,
  'Mat Pilates Dersleri - Esneklik & Core Gücü | Viva Studio',
  'Minder üzerinde kendi vücut ağırlığınızla esneklik kazanın, core kaslarınızı kuvvetlendirin. Doğru postür için mat pilates.',
  1
)
ON DUPLICATE KEY UPDATE
  slug = VALUES(slug),
  title = VALUES(title),
  short_description = VALUES(short_description),
  detail_description = VALUES(detail_description),
  category = VALUES(category),
  image_url = VALUES(image_url),
  video_url = VALUES(video_url),
  suitable_for = VALUES(suitable_for),
  benefits = VALUES(benefits),
  process = VALUES(process),
  faq = VALUES(faq),
  sort_order = VALUES(sort_order),
  seo_title = VALUES(seo_title),
  seo_description = VALUES(seo_description),
  is_active = VALUES(is_active);
